import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
const resultsDir=path.join(path.dirname(fileURLToPath(import.meta.url)),'results');fs.mkdirSync(resultsDir,{recursive:true});
const root=path.dirname(fileURLToPath(import.meta.url));
const html=()=>fs.readFileSync(path.join(root,'public','index.html'),'utf8');
// Shared runtime dependencies live inside the sibling legacy variant, never in an external installation.
const legacyRoot=path.resolve(root,'..','legacy-order');
const requireOld=createRequire(path.join(legacyRoot,'package.json'));
const keytar=requireOld('keytar');
const VAULT_SERVICE='new-product-order-workbench',VAULT_ACCOUNT='purchase-login';
const chromeProfile=path.join(process.env.LOCALAPPDATA||'C:/Users/admin/AppData/Local','新品下单模块Chrome');
const chromeCandidates=[path.join(process.env.LOCALAPPDATA||'','Google','Chrome','Application','chrome.exe'),'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function ensureBrowser(){try{const r=await fetch('http://127.0.0.1:9333/json/version');if(r.ok)return}catch{}const chrome=chromeCandidates.find(x=>fs.existsSync(x));if(!chrome)throw new Error('未找到 Google Chrome。');fs.mkdirSync(chromeProfile,{recursive:true});spawn(chrome,['--remote-debugging-port=9333',`--user-data-dir=${chromeProfile}`],{detached:true,stdio:'ignore',windowsHide:true}).unref();for(let i=0;i<20;i++){await sleep(500);try{if((await fetch('http://127.0.0.1:9333/json/version')).ok)return}catch{}}throw new Error('专用采购浏览器启动超时。')}
async function readJson(req){let raw='';for await(const c of req)raw+=c;if(raw.length>100000)throw new Error('请求过大');return JSON.parse(raw||'{}')}
function json(res,status,value){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function writeResult(results){const id=Date.now().toString(),file=path.join(resultsDir,`新品下单-${new Date().toISOString().slice(0,10)}-${id}.csv`);const lines=[['料号','数量','是否异常','订单创建','执行结果','异常说明 / 系统原始提示'].map(csvCell).join(',')];for(const x of results)lines.push([x.sku,x.quantity,x.ok===false?'是':'否',x.orderNo||'未创建',x.ok===false?'执行失败':(x.result||'完成'),x.error||x.success||''].map(csvCell).join(','));fs.writeFileSync(file,'\ufeff'+lines.join('\r\n'),'utf8');return {id,file}}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='GET'&&(req.url==='/'||req.url==='/index.html')){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(html())}
 if(req.method==='GET'&&req.url==='/vendor/xlsx.full.min.js'){res.writeHead(200,{'Content-Type':'application/javascript','Cache-Control':'no-store'});return fs.createReadStream(path.join(legacyRoot,'node_modules','xlsx','dist','xlsx.full.min.js')).pipe(res)}
 if(req.method==='GET'&&req.url==='/download/template'){const file=path.join(root,'新品下单任务模板.xlsx');if(!fs.existsSync(file))return json(res,404,{error:'Excel 模板文件不存在。'});res.writeHead(200,{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':"attachment; filename*=UTF-8''%E6%96%B0%E5%93%81%E4%B8%8B%E5%8D%95%E4%BB%BB%E5%8A%A1%E6%A8%A1%E6%9D%BF.xlsx",'Cache-Control':'no-store'});return fs.createReadStream(file).pipe(res)}
 if(req.method==='GET'&&req.url==='/health')return json(res,200,{status:'ok',mode:'connected',writesEnabled:true});
 if(req.method==='GET'&&req.url==='/api/account')return json(res,200,{credentialSaved:!!await keytar.getPassword(VAULT_SERVICE,VAULT_ACCOUNT)});
 if(req.method==='POST'&&req.url==='/api/account'){const x=await readJson(req);if(!String(x.username||'').trim()||!String(x.password||''))return json(res,400,{error:'请填写采购账号和密码。'});if(x.save)await keytar.setPassword(VAULT_SERVICE,VAULT_ACCOUNT,JSON.stringify({username:String(x.username).trim(),password:String(x.password)}));return json(res,200,{ok:true,credentialSaved:!!x.save})}
 if(req.method==='DELETE'&&req.url==='/api/account'){await keytar.deletePassword(VAULT_SERVICE,VAULT_ACCOUNT);return json(res,200,{ok:true})}
 if(req.method==='POST'&&req.url==='/api/login'){const x=await readJson(req);let login=null;if(String(x.username||'').trim()&&String(x.password||''))login={username:String(x.username).trim(),password:String(x.password)};else{const raw=await keytar.getPassword(VAULT_SERVICE,VAULT_ACCOUNT);if(raw)login=JSON.parse(raw)}if(!login)return json(res,400,{error:'请填写账号密码，或勾选长期保存后再使用自动登录。'});await ensureBrowser();const script=path.join(root,'purchase-login.mjs');const child=spawn(process.execPath,[script],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,NEW_PRODUCT_LOGIN:JSON.stringify(login)}});let out='',err='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('close',code=>{if(code===0)json(res,200,{ok:true,message:out.trim()||'已提交登录请求。'});else json(res,500,{error:(err||out||'登录失败').slice(-800)})});return}
 if(req.method==='POST'&&req.url==='/api/run'){const x=await readJson(req);const tasks=Array.isArray(x.tasks)?x.tasks.map(v=>({sku:String(v?.sku||'').trim(),quantity:Number(v?.quantity)})).filter(v=>v.sku&&v.quantity>0):(Array.isArray(x.skus)?x.skus.map(v=>({sku:String(v||'').trim(),quantity:1})).filter(v=>v.sku):[{sku:String(x.sku||'').trim(),quantity:Number(x.quantity||1)}].filter(v=>v.sku&&v.quantity>0));const mode=x.mode==='SUBMIT'?'SUBMIT':'DRY_RUN';if(!tasks.length)return json(res,400,{error:'请上传包含料号和数量的 Excel。'});if(tasks.length>100)return json(res,400,{error:'单次最多处理 100 条料号。'});if(mode==='SUBMIT'&&x.confirm!==true)return json(res,400,{error:'正式新品下单需要勾选“已确认创建真实采购订单”。'});await ensureBrowser();const results=[];for(const task of tasks){const {sku,quantity}=task;const child=spawn(process.execPath,[path.join(root,'new-product-runner.mjs')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,NEW_PRODUCT_SKU:sku,NEW_PRODUCT_QTY:String(quantity),NEW_PRODUCT_MODE:mode,NEW_PRODUCT_AUTHORIZED:mode==='SUBMIT'?'YES':'NO'}});let out='',err='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);const result=await new Promise(resolve=>child.on('close',code=>{if(code===0){try{return resolve({sku,quantity,ok:true,...JSON.parse(out)})}catch{return resolve({sku,quantity,ok:true,result:out.trim()})}}resolve({sku,quantity,ok:false,result:'未创建订单',error:(err||out||'执行失败').slice(-1200)})}));results.push(result)}const saved=writeResult(results);return json(res,200,{ok:true,id:saved.id,total:tasks.length,results})}
 if(req.method==='GET'&&req.url?.startsWith('/api/download/')){const id=path.basename(req.url);const file=fs.readdirSync(resultsDir).find(x=>x.includes(`-${id}.csv`));if(!file)return json(res,404,{error:'结果文件不存在'});res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(file)}`});return fs.createReadStream(path.join(resultsDir,file)).pipe(res)}
 json(res,404,{error:'not_found'});
}catch(e){json(res,500,{error:String(e.message||e)})}});
server.listen(8790,'127.0.0.1',()=>console.log('NEW_PRODUCT_DEMO=http://127.0.0.1:8790'));
