import express from 'express';import multer from 'multer';import fs from 'node:fs';import path from 'node:path';import {execFile,spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import keytar from 'keytar';import {readJson,writeJson,beijingNow} from './lib/state.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),app=express(),uploadDir=path.join(root,'uploads'),settingsFile=path.join(root,'settings.json'),progressFile=path.join(root,'progress.json'),stateFile=path.join(root,'state.json'),chromeProfile=path.join(process.env.LOCALAPPDATA||'C:/Users/admin/AppData/Local','老品下单工作台Chrome');fs.mkdirSync(uploadDir,{recursive:true});
const defaults={outputDir:path.join(process.env.USERPROFILE||'C:/Users/admin','Desktop','老品下单结果')};const settings=()=>{try{return {...defaults,...JSON.parse(fs.readFileSync(settingsFile,'utf8'))}}catch{return defaults}};const save=s=>fs.writeFileSync(settingsFile,JSON.stringify(s,null,2));
const upload=multer({dest:uploadDir,limits:{fileSize:20*1024*1024},fileFilter:(q,f,cb)=>cb(null,/\.xlsx$/i.test(f.originalname))});app.use(express.static(path.join(root,'public')));app.use(express.json());let active=null;const history=[];
const run=(cmd,args,opt={})=>new Promise((ok,bad)=>execFile(cmd,args,{cwd:root,windowsHide:true,maxBuffer:4*1024*1024,...opt},(e,stdout,stderr)=>e?bad(Object.assign(e,{stdout,stderr})):ok({stdout,stderr})));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));fs.rmSync(progressFile,{force:true});
async function ensureBrowser(){try{const r=await fetch('http://127.0.0.1:9333/json/version');if(r.ok)return}catch{}const candidates=[path.join(process.env.LOCALAPPDATA||'','Google','Chrome','Application','chrome.exe'),'C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'];const chrome=candidates.find(x=>fs.existsSync(x));if(!chrome)throw new Error('未找到 Google Chrome，无法启动专用采购浏览器。');fs.mkdirSync(chromeProfile,{recursive:true});spawn(chrome,['--remote-debugging-port=9333',`--user-data-dir=${chromeProfile}`],{detached:true,stdio:'ignore',windowsHide:true}).unref();for(let i=0;i<15;i++){await sleep(500);try{const r=await fetch('http://127.0.0.1:9333/json/version');if(r.ok)return}catch{}}throw new Error('专用采购浏览器启动超时。');}
app.get('/api/settings',(q,r)=>r.json({...settings(),credentialSaved:false}));
app.post('/api/settings',async(q,r)=>{const s={...settings(),outputDir:String(q.body.outputDir||defaults.outputDir).trim()};try{fs.mkdirSync(s.outputDir,{recursive:true})}catch{return r.status(400).json({error:'输出目录无法创建'})}save(s);if(q.body.username&&q.body.password){await keytar.setPassword('legacy-procurement-workbench','purchase-login',JSON.stringify({username:q.body.username,password:q.body.password}));}r.json({...s,credentialSaved:!!q.body.password});});
function progress(){return readJson(progressFile,{})||{}}
function persistedHistory(){return readJson(stateFile,{history:[]})?.history||[]}
function saveHistory(){writeJson(stateFile,{history:history.slice(0,50)})}
app.get('/api/status',(q,r)=>{const p=progress();if(active)active={...active,progress:p};const stored=[...history,...persistedHistory().filter(x=>!history.some(y=>y.id===x.id))];r.json({active,progress:p,history:stored.slice(0,15)})});
app.post('/api/run',upload.single('workbook'),async(q,r)=>{if(active)return r.status(409).json({error:'已有任务正在执行'});if(!q.file)return r.status(400).json({error:'请上传 .xlsx 文件'});const mode=q.body.mode==='full-production'?'full-production':'dry-run';if(mode==='full-production'&&q.body.confirm!=='YES')return r.status(400).json({error:'正式执行需要确认'});const s=settings(),out=String(q.body.outputDir||s.outputDir).trim();try{fs.mkdirSync(out,{recursive:true})}catch{return r.status(400).json({error:'输出目录无法创建'})}save({...s,outputDir:out});const pauseFile=path.join(root,`pause-${Date.now()}.flag`);
 const input=path.join(uploadDir,`${Date.now()}-${q.file.originalname.replace(/[^\w.\-\u4e00-\u9fa5]/g,'_')}`);fs.renameSync(q.file.path,input);
 const enteredUser=String(q.body.username||'').trim(),enteredPass=String(q.body.password||'');let login=null;
 if(enteredUser&&enteredPass){login={username:enteredUser,password:enteredPass};if(String(q.body.saveLogin||'')==='on')await keytar.setPassword('legacy-procurement-workbench','purchase-login',JSON.stringify(login));}
 else{try{login=JSON.parse(await keytar.getPassword('legacy-procurement-workbench','purchase-login')||'null')}catch{}}
 try{await ensureBrowser()}catch(e){return r.status(500).json({error:e.message})}
 const config={cdpUrl:'http://127.0.0.1:9333',inputWorkbook:input,sheetName:'下单任务',mode,progressFile,pauseFile,login};writeJson(path.join(root,'config.json'),config);fs.rmSync(progressFile,{force:true});const id=Date.now().toString();active={id,mode,status:'运行中',startedAt:beijingNow(),file:q.file.originalname,outputDir:out,pauseFile};r.json(active);const env={...process.env};if(mode==='full-production')env.PURCHASE_APPROVED='YES';run(process.execPath,['runner.mjs',`--mode=${mode}`],{env,timeout:600000}).then(({stdout})=>{const match=stdout.trim().match(/\{[\s\S]*\}$/);if(!match)throw new Error('执行器未返回结果清单');const p=JSON.parse(match[0]),final=path.join(out,path.basename(p.output));fs.copyFileSync(p.output,final);const paused=p.ledger?.some(x=>x.status==='已暂停');const done={...active,status:paused?'已暂停':'完成',endedAt:p.completedAt||beijingNow(),result:final,runDir:p.runDir,ledger:p.ledger,progress:{step:paused?'任务已暂停':'全部完成',completedAt:p.completedAt||beijingNow(),output:final}};history.unshift(done);saveHistory();active=null;writeJson(progressFile,done.progress)}).catch(e=>{const failed={...active,status:'异常',endedAt:beijingNow(),error:(e.stderr||e.message).slice(-1600),progress:{step:'执行异常',error:(e.stderr||e.message).slice(-1600)}};history.unshift(failed);saveHistory();active=null;writeJson(progressFile,failed.progress)});});
app.post('/api/pause',async(q,r)=>{if(!active)return r.status(409).json({error:'没有正在运行的任务'});fs.writeFileSync(active.pauseFile,'pause');active={...active,status:'暂停请求已发送'};r.json(active)});
app.get('/api/download/:id',(q,r)=>{const x=[...history,...persistedHistory()].find(x=>x.id===q.params.id);if(!x?.result||!fs.existsSync(x.result))return r.status(404).json({error:'结果文件不存在或任务记录已失效'});r.download(x.result,path.basename(x.result))});app.listen(8787,'127.0.0.1',()=>console.log('WORKBENCH=http://127.0.0.1:8787'));
